Clean codes
mikankari/yeahcheese pull request #6
Opened 2018-04-11 10:48 UTC by mikankari

コーディング規約やレビューを反映したPRです。

コンフリクトを懸念して、反映専用ブランチとしています。
DB関係の反映はブランチが独立しているため、 #1 に反映があります。

質問が１つあります。
DBのフィールド名はフレームワークの命名規則などの影響があると考えますが、
ここでの適切な規則は何かありますでしょうか。
よろしくお願いします。

レビューのTODO
- [ ] DBフィールド名
- [ ] Git のユーザ設定

2018-04-11 14:19 UTC, rymiyamoto commented
@mikankari 
- DBのフィールド命名について
  - postgresqlは大文字を無視するので、スネークケースで記述するのが望ましい
  - 主キーについては `id` で統一するのであれば、それで問題ないかなと
  - カラム名はどんなデータが入っているかを明記するのが良く、データの状態(hashとかbase64)だと「もとは何が入ってるの？」ってなるので気を付けてほしい
- Git のユーザ設定
  - 最低限以下のことをしておかないと、コミットログが「誰書いたん？」ってなるのでやっておいて(Organizationならなおさら)
  - https://git-scm.com/book/ja/v1/使い始める-最初のGitの構成#個人の識別情報

2018-04-11 15:32 UTC, rymiyamoto requested changes
以下気になる点です。
分からなかったらslackのDMなりグループチャンネルでメンションくださ～い

2018-04-11 15:32 UTC, rymiyamoto commented on .gitignore
> +/www/upload/
ファイル末尾の空行なしはpsr-2のコーディング規約に反するので直しておいてください
参考にpsr-2関連のもの貼っておくので一読してみてください
- [詳しいやつ](http://www.infiniteloop.co.jp/docs/psr/psr-2-coding-style-guide.html)
- [ゆるいやつ](https://www.slideshare.net/wterada/psr1-psr2-5)

2018-04-11 15:32 UTC, rymiyamoto commented on app/action/Event/Edit.php
> +        if ($end->getTimestamp() < $start->getTimestamp()) {
リファクタなのでスルーでもいいですが、オブジェクトのまま比較できるので
```php
if ($end < $start) {
    // 処理
}
```
みたいか感じにできるよ

2018-04-11 15:32 UTC, rymiyamoto commented on app/action/Event/Edit.php
> +            if (!in_array($photo['type'], Yeahcheese_Form_EventEdit::PHOTO_ACCEPT_TYPES, true)) {
同一クラス内であれば
`self::PHOTO_ACCEPT_TYPES`
みたいにかけるよ
(以下同様)

2018-04-11 15:32 UTC, rymiyamoto commented on app/Yeahcheese_EventManager.php
> +        return $this->db->getRow('SELECT * FROM events WHERE id = ?', [
`$this->db` ですが、これはコンストラクタで事前に `$db = $backend->getDB();` とプロパティに入れる必要があるので使うならこんな感じ
```php
/**
 *  コンストラクタ
 *
 *  @param  Ethna_Backend $backend
 */
public function __construct(\Ethna_Backend $backend)
{
    parent::__construct($backend);
    $this->db = $backend->getDB();
}
```
ちなみに[プロパティの定義自体は親クラスですでにされている](https://github.com/ethnamphp/ethnam/blob/a23548ae70d43366ba0e1f88341172bc73e387ec/src/AppManager.php#L29)ので記述は不要

2018-04-11 15:32 UTC, rymiyamoto commented on app/Yeahcheese_EventManager.php
> +            $formVars['name'],
`name` 二番目では？

2018-04-11 15:32 UTC, rymiyamoto commented on app/action/Event/Edit.php
> +        if (!$isSendForm || $isSendForm && $this->action_form->validate() > 0) {
フォーム値の妥当性は一番最初に確認するのが一般的なので、`$this->af->validate()` prepareの一番上に持ってくるべきかな。今回だったらこんな感じで
```php
public function prepare()
{
    if ($this->af->validate() > 0){
        return 'event_edit';
    }

    $this->userId = 1;  // 未実装のため仮データ
    $this->eventId = $this->action_form->get('event_id');
    // 以降後続処理
}
```

2018-04-11 15:32 UTC, rymiyamoto commented on app/action/Event/Edit.php
> +            'form_type' =>  FORM_TYPE_HIDDEN,
必須でない場合でも `required => false` は明記ておいたほうが、後から見るとき分かり易いです

2018-04-12 06:05 UTC, mikankari commented on app/Yeahcheese_EventManager.php
> +        return $this->db->getRow('SELECT * FROM events WHERE id = ?', [
ドキュメントいわく
> Ethna_AppManagerのコンストラクタにより、既にDBオブジェクトは 取得されています
> https://github.com/ethnamphp/ethnam/blob/master/doc/db.md#appmanager内でのdbオブジェクトの使用方法

とのことです。

2018-04-12 07:07 UTC, rymiyamoto commented on app/Yeahcheese_EventManager.php
> +        return $this->db->getRow('SELECT * FROM events WHERE id = ?', [
> ドキュメントいわく
>> Ethna_AppManagerのコンストラクタにより、既にDBオブジェクトは 取得されています
>> https://github.com/ethnamphp/ethnam/blob/master/doc/db.md#appmanager内でのdbオブジェクトの使用方法
> とのことです。
> 
ごめんごめんうちのサービスのと混ざってた
問題ないよー

2018-04-12 07:24 UTC, rymiyamoto approved these changes
確認しました、問題ないかと思います
親ブランチにマージしちゃってください〜
(#7 がレビューしにくいので早めによろしく）

2018-04-12 09:18 UTC, merged