Add authencating events
mikankari/yeahcheese pull request #7
Opened 2018-04-12 06:10 UTC by mikankari

閲覧者のログインとログアウトです。
レビューとマージをお願いします。

2018-04-12 09:39 UTC, rymiyamoto commented
@mikankari 
developmentの最新取り込んでもらえる？
developmentをこのブランチにmergeすれば解決するはず

2018-04-12 09:56 UTC, mikankari commented
@rymiyamoto 
対応しました。見づらくなり失礼いたしました。

2018-04-12 14:23 UTC, rymiyamoto requested changes
以下気になる点です

2018-04-12 14:23 UTC, rymiyamoto commented on app/Yeahcheese_EventManager.php
> +    public function login(string $password): int
イベントIDない時false返してるから、そのときにエラーになるよ

一例として上げるなら、このメソッドではSQLでのID検索だけにして、[呼び出し元](https://github.com/mikankari/yeahcheese/pull/7/files#diff-1ac490a56fa3fbf20efa54184fec8f25R32)でセッションに$eventId 入れるのがいいのかな。ただその場合はメソッド名を変える必要はあるけどね。

自分のやりやすいように直しておいて

2018-04-12 14:23 UTC, rymiyamoto commented on app/Yeahcheese_EventManager.php
> +    public function getLoginEvent($userId, $eventId): array
こいつも戻り値がfalseのときがあるので型チェックでエラーになる
イベント情報を取得するわけだから空配列を失敗時に渡しても問題ないかなと思った

2018-04-16 01:51 UTC, FujimoriYuya commented on app/action/Event/Edit.php
>          $eventId = $this->action_form->get('event_id');
今回の改修箇所じゃないですが
`action_form` は略してもいいと思います
http://ethna.jp/doc/reference/actionform.html

2018-04-16 01:51 UTC, FujimoriYuya commented on app/Yeahcheese_PhotoManager.php
>          $insertId = $this->db->getOne('SELECT max(id) FROM photos');
既存の部分ですが
`insert`に成功した際にそのレコードの主キーを取得しようとしているんでしょうか
`primary`つけてるなら`lastval()`の方がいい気がします。(つけてなかったらすみません)
https://www.postgresql.jp/document/8.1/html/functions-sequence.html

2018-04-16 01:52 UTC, FujimoriYuya commented on app/Yeahcheese_EventManager.php
> +    private function generatePassword(): string
passwordだと違和感
認証キー なので `***key` の方がいい気がします。
(細かい改修なので変更なしでも問題はないですが)

2018-04-16 02:52 UTC, rymiyamoto approved these changes
Request changes のままだと マージしにくいからApprove にしときます

2018-04-16 03:19 UTC, mikankari commented
@FujimoriYuya 
- `action_form` の省略については慣れないため略さず書いています。
- `password` についてはDBのフィールド名にあわせています。

いずれも基本的な機能が一通りマージされた段階での変更を考えています。

2018-04-16 08:52 UTC, rymiyamoto reviewed
以下気になる点です

2018-04-16 08:52 UTC, rymiyamoto commented on app/Yeahcheese_PhotoManager.php
> +        $result = $this->db->execute('DELETE FROM photos where event_id = ? AND id IN (?)', [
確かIN句のプレースホルダーの場合は要素の数分の `?` が必要になるので、このままだと1つ目のみしか削除できません。

真面目にこのロジックを考えるのがベストですが、今回の場合は時間の問題もあるので(あまり良くはありませんが)回数分削除のSQLを叩いても構いません。

2018-04-16 08:52 UTC, rymiyamoto commented on app/action/Event/Login/Execute.php
> +        $event = $eventManager->getLoginEvent(false, $this->eventId);
false渡してしまうと、メソッドの引数の型チェックでTypeErrorになると思います。
他と合わせて、数値にしておくのが良いでしょう

2018-04-16 08:52 UTC, rymiyamoto commented on app/action/Event/Show.php
> +        $this->userId = false;  // 未実装のため仮データ
直し忘れ？

2018-04-16 08:52 UTC, rymiyamoto commented on app/action/Event/Edit.php
> +            $this->action_form->setApp('photos_base_url', Yeahcheese_PhotoManager::UPLOAD_URL);
なぜにスネークケース？
特に理由がないならば基本的に変数はキャメルケースで統一しておいて下さい

2018-04-17 01:53 UTC, rymiyamoto commented
@mikankari 
コンフリクトしてるので解消しておいて下さい

2018-04-17 02:40 UTC, rymiyamoto approved these changes
以下気になる点です。
細かい(おそらくミス？)ので修正してマージしておいて下さい（レビュー依頼不要）

2018-04-17 02:40 UTC, rymiyamoto commented on app/Yeahcheese_EventManager.php
> +     *  @param  int     $userId     共有者ユーザのID。イベントを追加したユーザと一致すれば取得します。閲覧者の場合は FALSE
コメントがfalseのままになってる

2018-04-17 02:40 UTC, rymiyamoto commented on app/action/Event/Edit/Execute.php
> +        if ($latest = ! $eventId) {
未実装部分かな？
どっちにしろ `$latest` には何も入っていないので、現状だと `if ($eventId != null)` みたいになってるけど意図したもの？

2018-04-17 02:51 UTC, rymiyamoto commented on app/action/Event/Edit/Execute.php
> +        if ($latest = ! $eventId) {
ごめん嘘付いた
代入して比較してるのね

2018-04-17 02:56 UTC, mikankari commented
了解いたしました。ありがとうございます！

2018-04-17 03:03 UTC, merged